version: '3.8'

services:
  web:
    build: .
    environment:
      - SERVICE_TYPE=web
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    command: python -m gunicorn app:app --bind 0.0.0.0:8000 --workers 4

  worker:
    build: .
    environment:
      - SERVICE_TYPE=worker
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    command: rq worker --url ${REDIS_URL}

  scheduler:
    build: .
    environment:
      - SERVICE_TYPE=scheduler
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    command: python scheduler.py