version: '3.8'

services:
  web:
    build: .
    environment:
      - SERVICE_TYPE=web
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - FLASK_ENV=development
      - FLASK_DEBUG=true
      - SECRET_KEY=dev-secret-key-only-for-testing
      - LOG_LEVEL=DEBUG
      - BITCOIN_NETWORK=regtest
    ports:
      - "8000:8000"
    depends_on:
      - mariadb
      - redis
    volumes:
      - ./logs:/app/logs
      - .:/app
    command: python -m gunicorn app:app --bind 0.0.0.0:8000 --workers 1 --reload

  worker:
    build: .
    environment:
      - SERVICE_TYPE=worker
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - FLASK_ENV=development
      - SECRET_KEY=dev-secret-key-only-for-testing
      - LOG_LEVEL=DEBUG
    depends_on:
      - mariadb
      - redis
    volumes:
      - ./logs:/app/logs
      - .:/app
    command: rq worker --url ${REDIS_URL}

  scheduler:
    build: .
    environment:
      - SERVICE_TYPE=scheduler
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - FLASK_ENV=development
      - SECRET_KEY=dev-secret-key-only-for-testing
      - LOG_LEVEL=DEBUG
    depends_on:
      - mariadb
      - redis
    volumes:
      - ./logs:/app/logs
      - .:/app
    command: python scheduler.py

  mariadb:
    image: mariadb:10.11
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=arkrelay
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mariadb_data:
  redis_data: