"""Add Ark Relay models

Revision ID: e25db603fb30
Revises: 1afd22ad4d71
Create Date: 2025-09-21 12:33:33.842980

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e25db603fb30'
down_revision = '1afd22ad4d71'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('asset_type', sa.String(length=20), nullable=True),
    sa.Column('decimal_places', sa.Integer(), nullable=True),
    sa.Column('total_supply', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('metadata', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id')
    )
    op.create_table('signing_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('challenge_data', sa.LargeBinary(), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('signature', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['signing_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id')
    )
    op.create_table('signing_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('user_pubkey', sa.String(length=66), nullable=False),
    sa.Column('session_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('challenge_id', sa.String(length=64), nullable=True),
    sa.Column('intent_data', mysql.JSON(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('signed_tx', sa.Text(), nullable=True),
    sa.Column('result_data', mysql.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['signing_challenges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('asset_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_pubkey', sa.String(length=66), nullable=False),
    sa.Column('asset_id', sa.String(length=64), nullable=False),
    sa.Column('balance', sa.BigInteger(), nullable=True),
    sa.Column('reserved_balance', sa.BigInteger(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lightning_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_hash', sa.String(length=64), nullable=False),
    sa.Column('bolt11_invoice', sa.Text(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('amount_sats', sa.BigInteger(), nullable=False),
    sa.Column('asset_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('invoice_type', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('preimage', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['signing_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_hash')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('txid', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('tx_type', sa.String(length=20), nullable=False),
    sa.Column('raw_tx', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('amount_sats', sa.BigInteger(), nullable=False),
    sa.Column('fee_sats', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('block_height', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['signing_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('txid')
    )
    op.create_table('vtxos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vtxo_id', sa.String(length=64), nullable=False),
    sa.Column('txid', sa.String(length=64), nullable=False),
    sa.Column('vout', sa.Integer(), nullable=False),
    sa.Column('amount_sats', sa.BigInteger(), nullable=False),
    sa.Column('script_pubkey', sa.LargeBinary(), nullable=False),
    sa.Column('asset_id', sa.String(length=64), nullable=True),
    sa.Column('user_pubkey', sa.String(length=66), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('spending_txid', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vtxo_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vtxos')
    op.drop_table('transactions')
    op.drop_table('lightning_invoices')
    op.drop_table('asset_balances')
    op.drop_table('signing_sessions')
    op.drop_table('signing_challenges')
    op.drop_table('assets')
    # ### end Alembic commands ###