name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  python:
    name: Python Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gateway
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up uv
        uses: astral-sh/setup-uv@v3

      - name: Install deps
        run: |
          uv sync --frozen || uv sync

      - name: Run pytest (default subset)
        run: |
          uv run pytest -q

  typescript:
    name: TypeScript Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gateway/sdk-ts
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build
